import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LogInButton from "@/components/LogInButton";
import AuthModal from "@/components/AuthModal";
import Sidebar from "@/components/Sidebar";
import TextArea from "@/components/TextArea";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 m-0 p-0 h-screen flex flex-col">
        <LogInButton />
        <main className="flex">
          <Sidebar />
          <TextArea />
          {children}
        </main>
      </body>
    </html>
  );
}
